name: Train and (maybe) Release Model

on:
  push:
    # When a tag is pushed (ex: v1.0.0), trigger a release
    tags:
      - 'v*'
    # When some files are modified, trigger only a training
    paths:
      - '**.py'
      - requirements.txt
  pull_request:
    paths:
      - '**.py'
      - requirements.txt

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up dataset
        run: python setup_dataset.py

      - name: Train and export model
        run: python train.py

      - name: Upload model as artifact (PR only)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            build/fairscan-quadrilateral.pt
            build/fairscan-quadrilateral.tflite
            build/LICENSE.txt

      - name: Check if this is a release
        id: release_check
        run: |
          echo "release=${{ startsWith(github.ref, 'refs/tags/') }}" >> $GITHUB_OUTPUT

      - name: Upload release assets
        if: steps.release_check.outputs.release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/fairscan-quadrilateral.pt
            build/fairscan-quadrilateral.tflite
            build/LICENSE.txt
